### ISSUE TITLE
Response headers can't be changed

### ISSUE THREAD

**Issue by SomeComputerNerd** [didierfred/SimpleModifyHeaders#10]
I wanted to use this extension to modify "cache-control" response headers received from server-side.

However, I have found that response headers can't be added or modified at all.

Create two nonsense headers, one for request and one for response:

![a](https://user-images.githubusercontent.com/48368965/54060057-eac7ce00-41c0-11e9-8c8a-a355ba49fff9.png)

Testing this:

![b](https://user-images.githubusercontent.com/48368965/54060064-f0bdaf00-41c0-11e9-9cf5-9673cfbd2cf4.png)

I normally use the fork Waterfox, but I tested in the above pictures with Firefox with a new profile.

Thank you for your help and time.

**Comment by didierfred** [comment]
It modify the header but unfortunately  you can't see it in the console . It seems firefox log the header before it is modified by the plugin . 
If you add a header "content-type" with value "text/plain" for all pages , you will see that the response header is modified since all page will be shown as plain text.
I didn't find a solution for this problem ...

**Comment by SomeComputerNerd** [comment]
You're right, it actually is doing its job. I didn't test thoroughly enough.  Thanks.
