### ISSUE TITLE
Headers are not injected into JS requests

### ISSUE THREAD

**Issue by fusion2222** [didierfred/SimpleModifyHeaders#15]
Hello, I am not sure if this should be an issue or not, but sometimes, website needs to use websocket connections, or any other AJAX / fetch requests, which are invoked by Javascript. These JS invoked requests do not have injected headers by SimpleModifyHeaders plugin. Is this intended?

It would be awesome if there is some kind of option to force javascript requests to use headers too.

**Comment by didierfred** [comment]
Hello,
It was not intended . 
I check documentation and unfortunately it 's not possible to modify js request to prevent deadlock , see extract of chrome documentation  (https://developer.chrome.com/extensions/webRequest) : 
_"Also synchronous XMLHttpRequests from your extension are hidden from blocking event handlers in order to prevent deadlocks."_

**Comment by alexolog** [comment]
Is it possible to do so in Firefox?
