### ISSUE TITLE
Firefox-404

### ISSUE THREAD

**Issue by AyeshaSalaam** [didierfred/SimpleModifyHeaders#28]
hi, 
i cannot find simple-modify-headers on firefox anymore. i wanted to install on new firefox instance. why? your tool is user friendly. will it be back on firefox?

**Comment by didierfred** [comment]
The extension has been suddenly disabled by Firefox team due to security policy rules . I was on holiday , i came back today and submit a new version to be in conformity with the policy. The process of validation can take time, in the meantime you can download the extension via github: 
https://github.com/didierfred/SimpleModifyHeaders/raw/master/package/SimpleModifyHeaders-Package%20v1.7.0.zip

and install it via file :

![image](https://user-images.githubusercontent.com/34892849/130145131-e29d422c-4a64-4d62-a443-d7035644e921.png)
