### ISSUE TITLE
User-Agent

### ISSUE THREAD

**Issue by StVol33** [didierfred/SimpleModifyHeaders#33]
Приветствую!
Подскажите, почему не работает  смена User-Agent на сайте https://online.vtb.ru в брузере ФФ 52
http://ipic.su/img/img7/fs/screenshot2021-10-20002.1634733461.jpg
http://ipic.su/img/img7/fs/screenshot2021-10-20001.1634733200.jpg

**Comment by didierfred** [comment]
The web page is probably detecting your browser via javascript code and not via the request header .

See for example : https://codepedia.info/editor-example?id=47

**Comment by StVol33** [comment]
Interesting! Then why, if I use the User Agent Switcher extension (https://chrispederick.com/work/user-agent-switcher/) and change the User Agent there to FF 92, then the site https://online.vtb.ru/ shows acceptable browser?
http://ipic.su/img/img7/fs/screenshot2021-10-31001.1635680353.jpg

**Comment by didierfred** [comment]
I add a look to the code of user-agent-switcher , it s because the plugin is not modify the header but is setting the user agent by setting  user preference via javascript https://github.com/chrispederick/user-agent-switcher/blob/c98c287ac7e20ebfd38cbb12fd59613cdabce368/development/source/content_common/useragentswitcher/useragentswitcher.js#L439
