### ISSUE TITLE
Not started/no headers send after upgrade to 1.6.3 in Firefox

### ISSUE THREAD

**Issue by schoeppe** [didierfred/SimpleModifyHeaders#8]
Version 1.6.3 does not work anymore in Firefox:
- no header gets send with previously working configuration

Removed and re-installed extension:
- no header gets send with example configuration (httpbin.org replaced with other known hostname)

Thank you for your efforts and a useful extension!

**Comment by schoeppe** [comment]
I am using the latest Firefox (63.0.3) on Ubuntu Linux.

The same configuration worked in latest Chrome. I noticed that the toolbar icon switched from gray to green when started. This was not the case in Firefox so I got back to it to reproduce:
**And suddenly it worked there, too.**

I tried again uninstall/re-install and had some other issues with the toolbar icon (it was not displayed at all, configuration/start/stop dropdown empty), after disabling and re-enabling the extension the icon was displayed and correctly reflected the start/stop state.

Maybe just some problems with my setup (Firefox on Linux)!?

Feel free to close this issue and thanks again for your work!

**Comment by didierfred** [comment]
When i tested my extension before release , i once get  a similar problem but never manage to reproduce it .  I think , It 's due to migration from previous version to version 1.6.3  

I changed the way to store the configuration . When migrating from old version , the configuration is transfered on the new storage , i suspect that this transfert could in some circonstances  not work properly 

Thanks for the comment

**Comment by Jeppa** [comment]
Version 1.6.3 is not working for me ,too.
Switching back to 1.6.1 and the icon goes green again!

**Comment by didierfred** [comment]
Finally reproduce and find the problem , version 1.6.6 should solve the problem
