### ISSUE TITLE
1.6.3 not working anymore

### ISSUE THREAD

**Issue by Jeppa** [didierfred/SimpleModifyHeaders#9]
As mentioned here : https://github.com/didierfred/SimpleModifyHeaders/issues/8 
i have issues with latest version 1.6.3 aswell.
Tested in Firefox 61.0.1 and 63.0.3, both are not working.
The icon remains gray.

Switching back to V 1.6.1 : all is OK again...

**Comment by didierfred** [comment]
I suspect the problem came from migration the configuration data from v1.6.1 to v1.6.3

So I check again on Firefox version 63.0.3 migrating from v1.6.1 to v1.6.3  with different configuration and i do not reproduce the problem. 

Did your restart firefox after update ? 

Could you try to first remove the add-on and then  install directly the version 1.6.3  (You can save your configuration before removing by using the export function ) ?

**Comment by Jeppa** [comment]
Ok,
I deinstalled it, restarted Firefox, installed 1.6.3 again, started it and it went green.
So far so good...
Now i restarted Firefox again and i can not activate it anymore. It stays gray...

Instalkled 1.6.1 : green

**Comment by didierfred** [comment]
Finally reproduce and find the problem , version 1.6.6 should solve the problem

**Comment by Jeppa** [comment]
;) 
Works great again! ;)
